language: go
sudo: false

go:
  - 1.7

cache:
  directories:
    - $GOPATH/src/github.com/ready-steady

install:
  - go get -d -t ./...
  - (cd $GOPATH/src/github.com/ready-steady/hdf5 && make install)
  - (cd $GOPATH/src/github.com/ready-steady/lapack && make install)
  - (cd $GOPATH/src/github.com/turing-complete/hotspot && make install)

script:
  - go test ./...
  - make -C run

notifications:
  email: false

addons:
  apt:
    packages:
      - gfortran
